-- [1]
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- [2]
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN, 1, 6) DESC;

-- [3]
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%'
AND (STUDENT_ADDRESS LIKE '%강원%' OR STUDENT_ADDRESS LIKE '%경기%')
ORDER BY STUDENT_NAME;

-- [4]
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY SUBSTR(PROFESSOR_SSN, 1, 6);

-- [5]
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;

-- [6]
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) 
ORDER BY STUDENT_NAME;

-- [7]
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- [8]
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);

-- [9]
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS TC, TB_CLASS_PROFESSOR TCR, TB_DEPARTMENT TD, TB_PROFESSOR TP
WHERE TC.DEPARTMENT_NO = TD.DEPARTMENT_NO
AND TC.CLASS_NO = TCR.CLASS_NO
AND TCR.PROFESSOR_NO = TP.PROFESSOR_NO
AND CATEGORY = '인문사회';

-- [10]
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

-- [11]
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE STUDENT_NO = 'A313047';

-- [12]
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007'
AND CLASS_NAME = '인간관계론'
ORDER BY TERM_NO;

-- [13]
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE PREATTENDING_CLASS_NO IS NULL AND CATEGORY = '예체능';

-- [14]
SELECT STUDENT_NAME 학생이름, NVL2(COACH_PROFESSOR_NO,PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT TS
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE TS.DEPARTMENT_NO = '020'
ORDER BY ENTRANCE_DATE;

-- [15]
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME 학과이름, ROUND(AVG(POINT),5) 평점
FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) > 4;

-- [16]
SELECT CLASS_NO, CLASS_NAME, ROUND(AVG(POINT),5)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
WHERE DEPARTMENT_NO = '034' AND CLASS_TYPE LIKE '%전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 3 DESC;

-- [17]
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
                        FROM TB_STUDENT 
                        WHERE STUDENT_NAME = '최경희');

-- [18]
SELECT ROWNUM, STUDENT_NO, STUDENT_NAME
FROM (
        SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)
        FROM TB_STUDENT
        JOIN TB_GRADE USING (STUDENT_NO)
        JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
        WHERE DEPARTMENT_NAME = '국어국문학과'
        GROUP BY STUDENT_NO, STUDENT_NAME
        ORDER BY 3 DESC
    )
WHERE ROWNUM = 1;

-- [19]
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '자연과학' 
GROUP BY DEPARTMENT_NAME;






