
DROP TABLE TODO_USER;
CREATE TABLE TODO_USER(
    ID VARCHAR2(10) PRIMARY KEY,
    PWD VARCHAR2(15) NOT NULL,
    NICKNAME VARCHAR2(24),
    EMAIL VARCHAR2(100) NOT NULL,
    JOIN_DATE DATE DEFAULT SYSDATE NOT NULL
    -- 기본값 + 제약조건 순서로 작성하는 게 문법
);

DROP TABLE TODO_LIST;
CREATE TABLE TODO_LIST(
    TODO_NO NUMBER PRIMARY KEY,
    CONTENT VARCHAR2(300) NOT NULL,
    STATUS NUMBER DEFAULT 1 CHECK ( STATUS IN (1, 2, 3)),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    USER_ID REFERENCES TODO_USER (ID) ON DELETE SET NULL
    -- FORIEN KEY USER_ID REFERENCES TODO_USER(ID)
);

DROP SEQUENCE SEQ_TNO;
CREATE SEQUENCE SEQ_TNO NOCYCLE NOCACHE;

COMMENT ON COLUMN TODO_LIST.STATUS IS '1:진행중, 2:완료, 3:삭제';