
CREATE USER C##WORKBOOK IDENTIFIED BY WORKBOOK;
GRANT CONNECT, RESOURCE TO C##WORKBOOK;
ALTER USER C##WORKBOOK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER C##MYBATIS QUOTA UNLIMITED ON USERS;