CREATE TABLE PRODUCT(
    PRODUCT_ID VARCHAR2(20) PRIMARY KEY,
    P_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(20),
    STOCK NUMBER NOT NULL
);

INSERT INTO PRODUCT VALUES (
'pid_ss4', '갤럭시북',2890000,'울트라 4',15
);

INSERT INTO PRODUCT VALUES (
'pid_ap16', '맥북',3490000,'프로 16',10
);


INSERT INTO PRODUCT VALUES (
'pid_lg16', '그램',2490000,'프로 16',20
);

commit;

comment on COLUMN PRODUCT.PRODUCT_ID IS '상품 아이디';
comment on COLUMN PRODUCT.P_NAME IS '상품명';
comment on COLUMN PRODUCT.PRICE IS '상품가격';
comment on COLUMN PRODUCT.DESCRIPTION IS '상품 상세 정보';
comment on COLUMN PRODUCT.STOCK IS '재고';


INSERT INTO PRODUCT VALUES ('as', '하이', 5222, '바이', 5);
UPDATE PRODUCT SET P_NAME = '안녕', PRICE = 130, DESCRIPTION = '그래', STOCK = 1 WHERE PRODUCT_id = 'as';
DELETE PRODUCT WHERE PRODUCT_ID = 'as';

SELECT * FROM PRODUCT WHERE P_NAME LIKE ('그램');
SELECT * FROM PRODUCT WHERE P_NAME LIKE '%' || '그램' || '%';