SELECT * FROM DBA_USERS;

CREATE USER C##TEST0228 IDENTIFIED BY TEST0228;
GRANT RESOURCE, CREATE SESSION, CONNECT TO C##TEST0228;
ALTER USER C##TEST0228 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;