-- 실습용 계정
-- 계정명 : WORKBOOK / 비밀번호 : WORKBOOK
CREATE USER C##WORKBOOK IDENTIFIED BY WORKBOOK;
GRANT CONNECT, RESOURCE TO C##WORKBOOK;
ALTER USER C##WORKBOOK DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;