-- [1]
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- [2]
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- [3]
ALTER TABLE TB_CATEGORY ADD CONSTRAINT TB_CATEGORY_NAME_PK PRIMARY KEY (NAME);

-- [4]
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

-- [5]
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);

-- [6]
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
--> 컬럼명 변경할 때는 결합하여 사용할 수 없음 (오류 발생)

-- [7]
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT TB_CATEGORY_NAME_PK TO PK_CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C008448 TO PK_CLASS_TYPE_NO;

-- [8]
INSERT INTO TB_CATEGORY VALUES('공학', 'Y');
-- INSERT INTO TB_CATEGORY (CATEGORY_NAME) VALUES ('자연과학'); --- Y가 기본값이기 때문에
INSERT INTO TB_CATEGORY VALUES('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES('인문사회', 'Y');
COMMIT;

-- [9]
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

-- [10]
GRANT CREATE VIEW TO C##WORKBOOK;   -- VIEW 생성 권한 부여

CREATE VIEW VW_학생일반정보 (학번, 학생이름, 주소)
AS (SELECT STUDENT_NO , STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT);

SELECT * FROM VW_학생일반정보;

-- [11]
CREATE VIEW VW_지도면담 (학생이름, 학과이름, 지도교수이름)
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, NVL(PROFESSOR_NAME, '지도교수 없음') 
FROM TB_STUDENT
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
ORDER BY 2;

SELECT * FROM VW_지도면담;

-- [12]
CREATE VIEW VW_학과별학생수 (DEPARTMENT_NAME, STUDENT_COUNT)
AS  SELECT DEPARTMENT_NAME, COUNT(*)
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME;

SELECT * FROM VW_학과별학생수;

-- [13]
SELECT * FROM VW_학생일반정보 WHERE 학번 = 'A213046';

UPDATE VW_학생일반정보
SET 학생이름 = '정혜영'
WHERE 학번 = 'A213046';

-- [14]
CREATE OR REPLACE VIEW VW_학생일반정보 (학번, 학생이름, 주소)
AS (SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS FROM TB_STUDENT)
WITH READ ONLY; -- 추가하기

-- [15]
SELECT 과목번호, 과목이름, "누적 수강생 수(명)"
FROM(SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름 , COUNT(*) "누적 수강생 수(명)"
        FROM TB_GRADE
        JOIN TB_CLASS USING (CLASS_NO)
        WHERE SUBSTR(TERM_NO,1,4) BETWEEN 2005 AND 2009
        GROUP BY CLASS_NO, CLASS_NAME
        ORDER BY 3 DESC)    --> FROM절에 사용된 서브쿼리를 '인라인 뷰'라고 표현함
WHERE ROWNUM <= 3;