------------------------------------ BASIC ------------------------------------

-- [1]
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- [2]
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- [3]
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001';

-- [4]
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';

-- [5]
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- [6]
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- [7]
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- [8]
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- [9]
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- [10]
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND STUDENT_ADDRESS LIKE '%전주%'
        AND EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002;
        
        
        
---------------------------------- FUNCTION -----------------------------------

-- [1]
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- [2]
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) <> 3;

-- [3]
SELECT PROFESSOR_NAME 교수이름, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6))) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1) = 1
ORDER BY 2;

-- [4]
SELECT SUBSTR(PROFESSOR_NAME,2)
FROM TB_PROFESSOR;

-- [5]
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) > 19;

-- [6]
SELECT TO_CHAR(TO_DATE(201225), 'DAY') FROM DUAL;

-- [7]
SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL;
-- 2099년 10월 11일
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL;
-- 2049년 10월 11일
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL;
-- 1999년 10월 11일
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL;
-- 2049년 10월 11일

-- [8]
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';
--> WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) < 2000;

-- [9]
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- [10]
SELECT DEPARTMENT_NO 학과번호, CAPACITY "학생수(명)"
FROM TB_DEPARTMENT;

-- [11]
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL
GROUP BY COACH_PROFESSOR_NO;

-- [12]
SELECT SUBSTR(TERM_NO,1,4) "년도", ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);

-- [13]
SELECT DEPARTMENT_NO "학과코드명", COUNT(ABSENCE_YN) "휴학생 수"
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- [14]
SELECT STUDENT_NAME "동일이름" , COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1;

-- [15]
SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), TERM_NO)
ORDER BY SUBSTR(TERM_NO,1,4);